### ISSUE TITLE
Server stops sending data when a 0x00  byte is in content

### ISSUE THREAD

**Issue by jojo2massol** [trungams/http-server#2]
I'm trying to send raw data with the server, but when I have null values in the content, the next bytes are all null. The file size is correct, but I assume it's due to the length header. This is how I did:
```cpp
    HttpResponse response(HttpStatusCode::Ok);
    // send the framebuffer to the client as an arraybuffer
    response.SetHeader("Content-Type", "arraybuffer");

    const char *framebuffer_ptr = (const char *)framebuffer;
    const std::string framebuffer_str = std::move(std::string(framebuffer_ptr, sizeof(framebuffer)));
    response.SetContent(framebuffer_str);
    
    
    // print framebuffer_str as hex values with 2 digits per byte
    for (uint16_t i = 0; i < sizeof(framebuffer); i++)
    {
      std::cout << std::hex << std::setfill('0') << std::setw(2) << (int)framebuffer[i];
    }
    std::cout << framebuffer_str << std::endl;
```
The bytes are correctly printing in the console of the program, but on the client, only the first bytes are received:
server cout:
```
1d de ab 41 cd 26 e6 41 79 0 a4 6f 0 a3 84 0 a3 87 0 a3 35 0 86 46 0 92 6d 0 a3 7c 0 a4 7a 0 a4 7a 0 a4 70 0 a3 
...
```
client :
```
1D DE AB 41 CD 26 E6 41 79 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
...
```
I can't find by myself where the problem is, I know that all these pointers conversions are not the best choice, but since the server is  minimal, there is no other type for adding content, and I think there is probably a condition where if the string have a null byte, stop sending data.

**Comment by jojo2massol** [comment]
found out it was in http_server.cc:221 strncpy makes the raw_response->buffer with the error in, while response_string seems OK.
![image](https://user-images.githubusercontent.com/54369031/181270684-fa6a841e-4e81-40ab-a0e2-b032d25ef23b.png)
I still don't know how to solve it.

**Comment by jojo2massol** [comment]
Finally foud out. This is a property of strncopy. When a null byte is met, everything is null then. See [https://m.cplusplus.com/reference/cstring/strncpy/](https://m.cplusplus.com/reference/cstring/strncpy/).
 Just need to replace `strncpy`by `memcpy` and everything is good then.

**Comment by trungams** [comment]
That's a very good catch. Thank you for resolving it
